api-gateway:
  image:
    repository: phuong273/api-gateway
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1

config-server:
  image:
    repository: phuong273/config-server
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1

discovery-server:
  image:
    repository: phuong273/discovery-server
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1

vets-service:
  image:
    repository: phuong273/vets-service
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1

customers-service:
  image:
    repository: phuong273/customers-service
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1

visits-server:
  image:
    repository: phuong273/visits-server
    tag: "latest"
    pullPolicy: IfNotPresent
