api-gateway:
  image:
    repository: phuong273/api-gateway
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1
  port: 8080

config-server:
  image:
    repository: phuong273/config-server
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1
  port: 8888

discovery-server:
  image:
    repository: phuong273/discovery-server
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1
  port: 8761

vets-service:
  image:
    repository: phuong273/vets-service
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1
  port: 8083

customers-service:
  image:
    repository: phuong273/customers-service
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1
  port: 8081

visits-server:
  image:
    repository: phuong273/visits-server
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1
  port: 8082

    
