apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
        - name: admin-server
          image: "{{ index .Values.services "admin-server" "image" }}:{{ index .Values.services "admin-server" "tag" }}"
          ports:
            - containerPort: {{ index .Values.services "admin-server" "port" }}
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: admin-server
            - name: CONFIG_SERVER_URL
              value: config-server:8888
          resources:
            limits:
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: admin-server
spec:
  type: ClusterIP
  selector:
    app: admin-server
  ports:
    - port: {{ index .Values.services "admin-server" "port" }}
      targetPort: {{ index .Values.services "admin-server" "port" }}
