apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: {{ index .Values "api-gateway" "replicaCount" }}
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image:  {{ index .Values "api-gateway" "image" "repository" }}:{{ index .Values "api-gateway" "image" "tag" }}
          ports:
            - containerPort: {{ index .Values "api-gateway" "port" }}
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: api-gateway
            - name: CONFIG_SERVER_URL
              value: config-server:{{ index .Values "config-server" "port" }}
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: {{ index .Values "global" "zipkin" "endpoint" }}
          resources:
            limits:
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  annotations: 
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: {{ index .Values "api-gateway" "port" }}
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - port: {{ index .Values "api-gateway" "port" }}
      targetPort: {{ index .Values "api-gateway" "port" }}
