apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service
spec:
  replicas: {{ index .Values "customers-service" "replicaCount" }}
  selector:
    matchLabels:
      app: customers-service
  template:
    metadata:
      labels:
        app: customers-service
    spec:
      containers:
        - name: customers-service
          image: {{ index .Values "customers-service" "image" "repository" }}:{{ index .Values "customers-service" "image" "tag" }}
          ports:
            - containerPort: {{ index .Values "customers-service" "port" }}
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: customers-service
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: {{ index .Values "global" "zipkin" "endpoint" }}  
          resources:
            limits:
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
  annotations: 
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: {{ index .Values "customers-service" "port" }}
spec:
  type: NodePort
  selector:
    app: customers-service
  ports:
    - port: {{ index .Values "customers-service" "port" }}
      targetPort: {{ index .Values "customers-service" "port" }}
