{{- $svc := index .Values.services "discovery-server" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: "{{ $svc.image }}:{{ $svc.tag }}"
          ports:
            - containerPort: {{ $svc.port }}
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: discovery-server
            - name: CONFIG_SERVER_URL
              value: config-server:8888
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://tracing-server.monitoring.svc.cluster.local:9411/api/v2/spans"
          resources:
            limits:
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  type: ClusterIP
  selector:
    app: discovery-server
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
