apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
spec:
  replicas: {{.Values.discovery-server.replicaCount}}
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: {{.Values.discovery-server.image.repository}}:{{.Values.discovery-server.image.tag}}
          ports:
            - containerPort: {{.Values.discovery-server.port}}
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: discovery-server
            - name: CONFIG_SERVER_URL
              value: config-server:{{.Values.config-server.port}}
          resources:
            limits:
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  type: NodePort
  selector:
    app: discovery-server
  ports:
    - port: {{.Values.discovery-server.port}}
      targetPort: {{.Values.discovery-server.port}}
