{{- if index .Values "vets-service" "enabled" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
spec:
  replicas: {{ index .Values "vets-service" "replicaCount" }}
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
        - name: vets-service
          image: {{ index .Values "vets-service" "image" "repository" }}:{{ index .Values "vets-service" "image" "tag" }}
          ports:
            - containerPort: {{ index .Values "vets-service" "port" }}
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: vets-service
            - name: CONFIG_SERVER_URL
              value: config-server:{{ index .Values "config-server" "port" }}
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: {{ index .Values "global" "zipkin" "endpoint" }}          
          resources:
            limits:
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: vets-service
  annotations: 
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "{{ index .Values "vets-service" "port" }}"
spec:
  type: NodePort
  selector:
    app: vets-service
  ports:
    - port: {{ index .Values "vets-service" "port" }}
      targetPort: {{ index .Values "vets-service" "port" }}
