apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
spec:
  replicas: {{ index .Values "vets-service" "replicaCount" }}
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
        - name: vets-service
          image: {{ index .Values "vets-service" "image" "repository" }}:{{ index .Values "vets-service" "image" "tag" }}
          ports:
            - containerPort: {{ index .Values "vets-service" "port" }}
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: vets-service
            - name: CONFIG_SERVER_URL
              value: config-server:{{ index .Values "config-server" "port" }}
          resources:
            limits:
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: vets-service
spec:
  type: NodePort
  selector:
    app: vets-service
  ports:
    - port: {{ index .Values "vets-service" "port" }}
      targetPort: {{ index .Values "vets-service" "port" }}
