apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
spec:
  replicas: {{ index .Values "visits-service" "replicaCount" }}
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      containers:
        - name: visits-service
          image: {{ index .Values "visits-service" "image" "repository" }}:{{ index .Values "visits-service" "image" "tag" }}
          ports:
            - containerPort: {{ index .Values "visits-service" "port" }}
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: visits-service
            - name: CONFIG_SERVER_URL
              value: config-server:{{ index .Values "config-server" "port" }}
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: {{ index .Values "global" "zipkin" "endpoint" }}           
          resources:
            limits:
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: visits-service
  annotations: 
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: {{ index .Values "visits-service" "port" }}
spec:
  type: NodePort
  selector:
    app: visits-service
  ports:
    - port: {{ index .Values "visits-service" "port" }}
      targetPort: {{ index .Values "visits-service" "port" }}
