apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      containers:
        - name: visits-service
          image: {{ index .Values.services "visits-service" "image" }}
          ports:
            - containerPort: {{ index .Values.services "visits-service" "port" }}
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: visits-service
            - name: CONFIG_SERVER_URL
              value: config-server:8888
          resources:
            limits:
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: visits-service
spec:
  type: ClusterIP
  selector:
    app: visits-service
  ports:
    - port: {{ index .Values.services "visits-service" "port" }}
      targetPort: {{ index .Values.services "visits-service" "port" }}
