{{- $svc := index .Values.services "visits-service" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      containers:
        - name: visits-service
          image: "{{ $svc.image }}:{{ $svc.tag }}"
          ports:
            - containerPort: {{ $svc.port }}
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: visits-service
            - name: CONFIG_SERVER_URL
              value: config-server:8888
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://tracing-server.monitoring.svc.cluster.local:9411/api/v2/spans"
          resources:
            limits:
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: visits-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "{{ $svc.port }}"
spec:
  type: ClusterIP
  selector:
    app: visits-service
  ports:
    - port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
