apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
spec:
  replicas: {{.Values.visits-service.replicaCount}}
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      containers:
        - name: visits-service
          image: {{.Values.visits-service.image.repository}}:{{.Values.visits-service.image.tag}}
          ports:
            - containerPort: {{.Values.visits-service.port}}
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: visits-service
            - name: CONFIG_SERVER_URL
              value: config-server:{{.Values.config-server.port}}
          resources:
            limits:
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: visits-service
spec:
  type: NodePort
  selector:
    app: visits-service
  ports:
    - port: {{.Values.visits-service.port}}
      targetPort: {{.Values.visits-service.port}}
